image: ubuntu/latest
packages:
  - curl
  - unzip
sources:
  - https://git.sr.ht/~ruivieira/srhtclient
tasks:
  - setup: |
      curl -fsSL https://deno.land/x/install/install.sh | sh
  - test: |
      cd srhtclient
      /home/build/.deno/bin/deno fmt --check */**.ts
      /home/build/.deno/bin/deno test -A --unstable tests/*.ts